name: hasba
description: "calculature."

version: 1.0.0+1

environment:
  sdk: ^3.5.0


dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.3.2
  vector_math: ^2.1.4

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0

flutter:


  uses-material-design: true

  assets:
    - assets/Imgs/


  fonts:
    - family: IBM
      fonts:
        - asset: assets/Fonts/IBMPlexSansArabic-Bold.ttf
